version: 0.2

levels:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      # - npm test - Incluir quando houver testes

artifacts:
    files:
      - .ebextensions/*
      - .platform/nginx/conf.d/*
      - dist/apps/calculator/main.js
      - package.json

# Incluir relatórios de testes 
# quando as APIs estiverem cobertas por testes. 

# https://docs.aws.amazon.com/codebuild/latest/userguide/test-report-jest.html

# reports:
#   jest_reports:
#     files:
#       - <report filename>
#     file-format: JUNITXML
#     base-directory: <test report directory>